### PR TITLE
#71 Add auto generated documentation to CI workflow

### LINKED ISSUE #71: Add auto generated documentation to CI workflow
This issue has been repurposed to generating automated documentation.

Auto generate code documentation and push to document repository.

~~Each resource helper should have documentation explaining its functionality. Once thorough helper comments are added to cmdlets, auto generation workflow should be run and generated markdowns should be PRd into main.~~
 
~~Acceptance Criteria:~~
~~- [ ] Documentation for each resource helper contract is checked into main~~

### PR DESCRIPTION
**Pull request by marclerwick**
Updated files related to publishing generated documentation to auto generate the documentation when the PowerShell module files have been updated and to also commit and push the changes to the docs branch if there are any files changed.
Added a pipeline for creating a PR when the docs branch has been pushed by the CI pipeline.

Closes #71

### CODE REVIEW

**Review by msha1026 — APPROVED** [review]
Oo nice these are cool changes!

**Comment by ozboms** [comment]
Why are we creating and checking out a branch when someone does a change to the documentation?

Specifically, why is it a separate docs branch?

**Comment by marclerwick** [comment]
@ozboms The update is a refactor of the existing code that also created a separate docs branch. The most significant reason to do this is so that a pull request can be generated from any changes that are made.

**Comment by msha1026** [comment]
> Why are we creating and checking out a branch when someone does a change to the documentation?
> 
> Specifically, why is it a separate docs branch?

Also, the platyPS PowerShell module auto generates markdown files by using the PowerShell help comments in our PowerShell code. So, a branch is created if those help comments are updated which causes a change in the markdowns generated. Since we cannot commit directly into main, a new branch (`docs` in this case) would need to be created and PR'd instead.

**Review by ozboms — APPROVED** [review]
Thanks for the explanations! Code looks good to me :)

**Pull request merged**
